---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "eslint"
        versions: [">=9.0.0"]
    groups:
      react-query:
        patterns:
          - "@tanstack/*"
      leaflet:
        patterns:
          - "@types/leaflet"
          - "leaflet"
          - "leaflet-*"
          - "react-leaflet"
          - "react-leaflet-*"
      react:
        patterns:
          - "@emoji-mart/*"
          - "@types/react"
          - "dayjs"
          - "emoji-mart"
          - "jwt-decode"
          - "react"
          - "react-*"
      mui:
        patterns:
          - "@emotion/*"
          - "@fontsource/*"
          - "@fortawesome/*"
          - "@mui/*"
      development:
        patterns:
          - "@testing-library/*"
          - "@types/*"
          - "@typescript-eslint/*"
          - "@vitejs/plugin-react"
          - "@vitest/coverage-v8"
          - "cssnano"
          - "eslint"
          - "eslint-*"
          - "jsdom"
          - "jwt-encode"
          - "postcss"
          - "postcss-*"
          - "prettier"
          - "typescript"
          - "vite"
          - "vitest"
          - "vitest-*"
