---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      react:
        patterns:
          - "@tanstack/*"
          - "@types/react"
          - "@types/react-helmet"
          - "react"
          - "react-*"
      mui:
        patterns:
          - "@emotion/*"
          - "@fontsource/*"
          - "@fortawesome/*"
          - "@mui/*"
      development:
        patterns:
          - "@babel/*"
          - "@testing-library/*"
          - "@types/*"
          - "@typescript-eslint/*"
          - "babel-*"
          - "css-loader"
          - "cssnano"
          - "dotenv"
          - "dotenv-*"
          - "eslint"
          - "eslint-*"
          - "file-loader"
          - "html-webpack-plugin"
          - "identity-obj-proxy"
          - "jest"
          - "jest-*"
          - "postcss"
          - "postcss-*"
          - "prettier"
          - "prettier-*"
          - "resolve"
          - "resolove-url-loader"
          - "style-loader"
          - "terser-webpack-plugin"
          - "ts-*"
          - "typescript"
          - "typescript-*"
          - "url-loader"
          - "webpack"
          - "webpack-*"
