name: Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier
        uses: wearerequired/lint-action@v2
        with:
          check_name: Prettier Results
          prettier: true
          prettier_dir: src

  eslint:
    name: ESLint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'src/'
          filter_mode: added
          fail_level: error
